// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Project1

#ifndef _PROJECT1_UI_H
#define _PROJECT1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_MainScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_img_ellipse_1_png);   // assets/img/Ellipse 1.png
LV_IMG_DECLARE( ui_img_img_start_png);   // assets/img/START.png
LV_IMG_DECLARE( ui_img_725341252);   // assets/img/GO!.png
LV_IMG_DECLARE( ui_img_img_player1_png);   // assets/img/player1.png
LV_IMG_DECLARE( ui_img_img_player2_png);   // assets/img/player2.png
LV_IMG_DECLARE( ui_img_img_player3_png);   // assets/img/player3.png
LV_IMG_DECLARE( ui_img_img_player4_png);   // assets/img/player4.png
LV_IMG_DECLARE( ui_img_img_group_winner_png);   // assets/img/Group Winner.png
LV_IMG_DECLARE( ui_img_img_pressjoyn_png);   // assets/img/pressJoyn.png
LV_IMG_DECLARE( ui_img_img_reactmode_png);   // assets/img/reactMode.png
LV_IMG_DECLARE( ui_img_img_shakemode_png);   // assets/img/shakeMode.png
LV_IMG_DECLARE( ui_img_img_deucemode_png);   // assets/img/deuceMode.png

// FONTS
LV_FONT_DECLARE( ui_font_MonserratBold64V2);
LV_FONT_DECLARE( ui_font_MontserratBold120);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
