// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Project1

#include "../ui.h"

lv_obj_t *ui_MainScreen = NULL;lv_obj_t *ui_centerCircle = NULL;lv_obj_t *ui_imgStart = NULL;lv_obj_t *ui_imgGo = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_player1 = NULL;lv_obj_t *ui_player2 = NULL;lv_obj_t *ui_player3 = NULL;lv_obj_t *ui_player4 = NULL;lv_obj_t *ui_labelCountDown = NULL;lv_obj_t *ui_labelPlayer1Timing = NULL;lv_obj_t *ui_labelPlayer2Timing = NULL;lv_obj_t *ui_labelPlayer3Timing = NULL;lv_obj_t *ui_labelPlayer4Timing = NULL;lv_obj_t *ui_imgWinner = NULL;lv_obj_t *ui_labelWinnerNum = NULL;lv_obj_t *ui_wifiNotOK = NULL;lv_obj_t *ui_wifiOk = NULL;lv_obj_t *ui_imgPressJoyn = NULL;lv_obj_t *ui_imgReactMode = NULL;lv_obj_t *ui_imgShakeMode = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_centerCircle = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_centerCircle, &ui_img_img_ellipse_1_png);
lv_obj_set_width( ui_centerCircle, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_centerCircle, LV_SIZE_CONTENT);   /// 320
lv_obj_set_x( ui_centerCircle, 12 );
lv_obj_set_y( ui_centerCircle, 72 );
lv_obj_set_align( ui_centerCircle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_centerCircle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_centerCircle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgStart = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgStart, &ui_img_img_start_png);
lv_obj_set_width( ui_imgStart, LV_SIZE_CONTENT);  /// 274
lv_obj_set_height( ui_imgStart, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_imgStart, 14 );
lv_obj_set_y( ui_imgStart, 70 );
lv_obj_set_align( ui_imgStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgStart, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgGo = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgGo, &ui_img_725341252);
lv_obj_set_width( ui_imgGo, LV_SIZE_CONTENT);  /// 143
lv_obj_set_height( ui_imgGo, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_imgGo, 11 );
lv_obj_set_y( ui_imgGo, 72 );
lv_obj_set_align( ui_imgGo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgGo, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgGo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel1, 150);
lv_obj_set_height( ui_Panel1, 150);
lv_obj_set_x( ui_Panel1, -293 );
lv_obj_set_y( ui_Panel1, -160 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel3, 150);
lv_obj_set_height( ui_Panel3, 150);
lv_obj_set_x( ui_Panel3, 103 );
lv_obj_set_y( ui_Panel3, -160 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel2, 150);
lv_obj_set_height( ui_Panel2, 150);
lv_obj_set_x( ui_Panel2, -92 );
lv_obj_set_y( ui_Panel2, -160 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel4, 150);
lv_obj_set_height( ui_Panel4, 150);
lv_obj_set_x( ui_Panel4, 295 );
lv_obj_set_y( ui_Panel4, -160 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel4, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_player1 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player1, &ui_img_img_player1_png);
lv_obj_set_width( ui_player1, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player1, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player1, -293 );
lv_obj_set_y( ui_player1, -152 );
lv_obj_set_align( ui_player1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player2 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player2, &ui_img_img_player2_png);
lv_obj_set_width( ui_player2, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player2, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player2, -90 );
lv_obj_set_y( ui_player2, -152 );
lv_obj_set_align( ui_player2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player3 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player3, &ui_img_img_player3_png);
lv_obj_set_width( ui_player3, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player3, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player3, 104 );
lv_obj_set_y( ui_player3, -152 );
lv_obj_set_align( ui_player3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_player4 = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_player4, &ui_img_img_player4_png);
lv_obj_set_width( ui_player4, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_player4, LV_SIZE_CONTENT);   /// 150
lv_obj_set_x( ui_player4, 296 );
lv_obj_set_y( ui_player4, -152 );
lv_obj_set_align( ui_player4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_player4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_player4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelCountDown = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_labelCountDown, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelCountDown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelCountDown, 10 );
lv_obj_set_y( ui_labelCountDown, 66 );
lv_obj_set_align( ui_labelCountDown, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelCountDown,"3");
lv_obj_add_flag( ui_labelCountDown, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_labelCountDown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelCountDown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelCountDown, &ui_font_MontserratBold120, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelPlayer1Timing = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_labelPlayer1Timing, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelPlayer1Timing, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelPlayer1Timing, -293 );
lv_obj_set_y( ui_labelPlayer1Timing, -53 );
lv_obj_set_align( ui_labelPlayer1Timing, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelPlayer1Timing,"0.231 ms");
lv_obj_add_flag( ui_labelPlayer1Timing, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_labelPlayer1Timing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelPlayer1Timing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelPlayer1Timing, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelPlayer2Timing = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_labelPlayer2Timing, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelPlayer2Timing, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelPlayer2Timing, -91 );
lv_obj_set_y( ui_labelPlayer2Timing, -53 );
lv_obj_set_align( ui_labelPlayer2Timing, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelPlayer2Timing,"0.231 ms");
lv_obj_add_flag( ui_labelPlayer2Timing, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_labelPlayer2Timing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelPlayer2Timing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelPlayer2Timing, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelPlayer3Timing = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_labelPlayer3Timing, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelPlayer3Timing, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelPlayer3Timing, 104 );
lv_obj_set_y( ui_labelPlayer3Timing, -53 );
lv_obj_set_align( ui_labelPlayer3Timing, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelPlayer3Timing,"0.231 ms");
lv_obj_add_flag( ui_labelPlayer3Timing, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_labelPlayer3Timing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelPlayer3Timing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelPlayer3Timing, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelPlayer4Timing = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_labelPlayer4Timing, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelPlayer4Timing, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelPlayer4Timing, 297 );
lv_obj_set_y( ui_labelPlayer4Timing, -53 );
lv_obj_set_align( ui_labelPlayer4Timing, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelPlayer4Timing,"0.231 ms");
lv_obj_add_flag( ui_labelPlayer4Timing, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_labelPlayer4Timing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelPlayer4Timing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelPlayer4Timing, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgWinner = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgWinner, &ui_img_img_group_winner_png);
lv_obj_set_width( ui_imgWinner, LV_SIZE_CONTENT);  /// 431
lv_obj_set_height( ui_imgWinner, LV_SIZE_CONTENT);   /// 207
lv_obj_set_x( ui_imgWinner, 1 );
lv_obj_set_y( ui_imgWinner, 106 );
lv_obj_set_align( ui_imgWinner, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgWinner, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgWinner, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelWinnerNum = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_labelWinnerNum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelWinnerNum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelWinnerNum, 109 );
lv_obj_set_y( ui_labelWinnerNum, 177 );
lv_obj_set_align( ui_labelWinnerNum, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelWinnerNum,"1");
lv_obj_add_flag( ui_labelWinnerNum, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_labelWinnerNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelWinnerNum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelWinnerNum, &ui_font_MonserratBold64V2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiNotOK = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_wifiNotOK, &ui_img_2097260803);
lv_obj_set_width( ui_wifiNotOK, LV_SIZE_CONTENT);  /// 512
lv_obj_set_height( ui_wifiNotOK, LV_SIZE_CONTENT);   /// 512
lv_obj_set_x( ui_wifiNotOK, -370 );
lv_obj_set_y( ui_wifiNotOK, 216 );
lv_obj_set_align( ui_wifiNotOK, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiNotOK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifiNotOK, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_wifiNotOK,16);

ui_wifiOk = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_wifiOk, &ui_img_1198241503);
lv_obj_set_width( ui_wifiOk, LV_SIZE_CONTENT);  /// 512
lv_obj_set_height( ui_wifiOk, LV_SIZE_CONTENT);   /// 512
lv_obj_set_x( ui_wifiOk, -370 );
lv_obj_set_y( ui_wifiOk, 216 );
lv_obj_set_align( ui_wifiOk, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifiOk, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_wifiOk,16);

ui_imgPressJoyn = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgPressJoyn, &ui_img_img_pressjoyn_png);
lv_obj_set_width( ui_imgPressJoyn, LV_SIZE_CONTENT);  /// 250
lv_obj_set_height( ui_imgPressJoyn, LV_SIZE_CONTENT);   /// 130
lv_obj_set_x( ui_imgPressJoyn, 13 );
lv_obj_set_y( ui_imgPressJoyn, 73 );
lv_obj_set_align( ui_imgPressJoyn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgPressJoyn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgPressJoyn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgReactMode = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgReactMode, &ui_img_img_reactmode_png);
lv_obj_set_width( ui_imgReactMode, LV_SIZE_CONTENT);  /// 263
lv_obj_set_height( ui_imgReactMode, LV_SIZE_CONTENT);   /// 130
lv_obj_set_x( ui_imgReactMode, 11 );
lv_obj_set_y( ui_imgReactMode, 76 );
lv_obj_set_align( ui_imgReactMode, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgReactMode, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgReactMode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgShakeMode = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_imgShakeMode, &ui_img_img_shakemode_png);
lv_obj_set_width( ui_imgShakeMode, LV_SIZE_CONTENT);  /// 276
lv_obj_set_height( ui_imgShakeMode, LV_SIZE_CONTENT);   /// 130
lv_obj_set_x( ui_imgShakeMode, 9 );
lv_obj_set_y( ui_imgShakeMode, 79 );
lv_obj_set_align( ui_imgShakeMode, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgShakeMode, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgShakeMode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_MainScreen_screen_destroy(void)
{
   if (ui_MainScreen) lv_obj_del(ui_MainScreen);

// NULL screen variables
ui_MainScreen= NULL;
ui_centerCircle= NULL;
ui_imgStart= NULL;
ui_imgGo= NULL;
ui_Panel1= NULL;
ui_Panel3= NULL;
ui_Panel2= NULL;
ui_Panel4= NULL;
ui_player1= NULL;
ui_player2= NULL;
ui_player3= NULL;
ui_player4= NULL;
ui_labelCountDown= NULL;
ui_labelPlayer1Timing= NULL;
ui_labelPlayer2Timing= NULL;
ui_labelPlayer3Timing= NULL;
ui_labelPlayer4Timing= NULL;
ui_imgWinner= NULL;
ui_labelWinnerNum= NULL;
ui_wifiNotOK= NULL;
ui_wifiOk= NULL;
ui_imgPressJoyn= NULL;
ui_imgReactMode= NULL;
ui_imgShakeMode= NULL;

}
